-- =============================================================================
-- Open Clinical Record (OCR) — COMPLETE PostgreSQL DATABASE SCRIPT
-- =============================================================================
-- Source of truth: EF Core entities + AppDbContext model.
-- Generated: 2026-09-15
--
-- HOW TO USE (from repository ROOT):
--   psql -U postgres -d open_clinical_record -f docs/05-data/ocr-complete-database.sql
-- Prefer for the live application: dotnet ef database update
--
-- IMPORTANT:
--   Patient history is retained. Patient-owned clinical records use RESTRICT
--   rather than cascade deletion. Patient lifecycle is handled through status/
--   inactivation and the death-record provenance model.
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- ASP.NET Core Identity
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL DEFAULT FALSE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    "FullName" character varying(200) NOT NULL DEFAULT '',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

-- -----------------------------------------------------------------------------
-- Patients
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Patients" (
    "Id" uuid NOT NULL,
    "MedicalRecordNumber" character varying(32) NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "DateOfBirth" date NULL,
    "Sex" character varying(32) NULL,
    "Status" character varying(32) NOT NULL DEFAULT 'Active',
    "NationalId" character varying(64) NULL,
    "Phone" character varying(40) NULL,
    "SecondaryPhone" character varying(40) NULL,
    "Email" character varying(256) NULL,
    "Address" character varying(256) NULL,
    "City" character varying(100) NULL,
    "EmergencyContactName" character varying(120) NULL,
    "PreferredLanguage" character varying(64) NULL,
    "InsuranceScheme" character varying(120) NULL,
    "Notes" character varying(500) NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Patients_Status" CHECK ("Status" IN ('Active', 'Inactive', 'Deceased'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Patients_MedicalRecordNumber" ON "Patients" ("MedicalRecordNumber");
CREATE INDEX IF NOT EXISTS "IX_Patients_LastName_FirstName" ON "Patients" ("LastName", "FirstName");

-- -----------------------------------------------------------------------------
-- Patient history / allergies
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "PatientAllergies" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Substance" character varying(200) NOT NULL,
    "Reaction" character varying(200) NULL,
    "Severity" character varying(32) NOT NULL DEFAULT 'Unknown',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_PatientAllergies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PatientAllergies_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_PatientAllergies_PatientId" ON "PatientAllergies" ("PatientId");

CREATE TABLE IF NOT EXISTS "MedicalHistoryItems" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Category" character varying(32) NOT NULL DEFAULT 'Condition',
    "Description" character varying(500) NOT NULL,
    "OnsetDate" date NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_MedicalHistoryItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicalHistoryItems_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_MedicalHistoryItems_PatientId" ON "MedicalHistoryItems" ("PatientId");

-- -----------------------------------------------------------------------------
-- Appointments and appointment event history
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Appointments" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "AppointmentDate" date NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "DurationMinutes" integer NOT NULL DEFAULT 30,
    "AppointmentType" character varying(40) NOT NULL DEFAULT 'Consultation',
    "Status" character varying(32) NOT NULL DEFAULT 'Scheduled',
    "ProviderUserId" character varying(450) NULL,
    "ProviderName" character varying(200) NULL,
    "Reason" character varying(500) NULL,
    "Notes" character varying(500) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_Appointments_AppointmentDate" ON "Appointments" ("AppointmentDate");
CREATE INDEX IF NOT EXISTS "IX_Appointments_PatientId" ON "Appointments" ("PatientId");
CREATE INDEX IF NOT EXISTS "IX_Appointments_Status" ON "Appointments" ("Status");

CREATE TABLE IF NOT EXISTS "AppointmentEvents" (
    "Id" uuid NOT NULL,
    "AppointmentId" uuid NOT NULL,
    "FromStatus" character varying(32) NOT NULL,
    "ToStatus" character varying(32) NOT NULL,
    "Reason" character varying(500) NULL,
    "ActorUserId" character varying(450) NULL,
    "ActorName" character varying(200) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_AppointmentEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppointmentEvents_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_AppointmentEvents_AppointmentId" ON "AppointmentEvents" ("AppointmentId");

-- -----------------------------------------------------------------------------
-- Clinical visits / encounter records
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ClinicalVisits" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "AppointmentId" uuid NULL,
    "VisitDate" timestamp with time zone NOT NULL DEFAULT NOW(),
    "VisitType" character varying(40) NOT NULL DEFAULT 'Consultation',
    "Status" character varying(32) NOT NULL DEFAULT 'Draft',
    "EpisodeLabel" character varying(200) NULL,
    "Location" character varying(120) NULL,
    "Department" character varying(120) NULL,
    "ChiefComplaint" character varying(500) NULL,
    "Plan" character varying(1000) NULL,
    "Instructions" character varying(500) NULL,
    "ClinicianUserId" character varying(450) NULL,
    "ClinicianName" character varying(200) NULL,
    "CheckInAt" timestamp with time zone NULL,
    "CheckOutAt" timestamp with time zone NULL,
    "FinalizedAt" timestamp with time zone NULL,
    "FinalizedByUserId" character varying(450) NULL,
    "FinalizedByName" character varying(200) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ClinicalVisits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClinicalVisits_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ClinicalVisits_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "CK_ClinicalVisits_Status" CHECK ("Status" IN ('Draft', 'Final', 'Cancelled'))
);
CREATE INDEX IF NOT EXISTS "IX_ClinicalVisits_PatientId" ON "ClinicalVisits" ("PatientId");
CREATE INDEX IF NOT EXISTS "IX_ClinicalVisits_PatientId_VisitDate" ON "ClinicalVisits" ("PatientId", "VisitDate");
CREATE INDEX IF NOT EXISTS "IX_ClinicalVisits_AppointmentId" ON "ClinicalVisits" ("AppointmentId");

CREATE TABLE IF NOT EXISTS "VitalSigns" (
    "Id" uuid NOT NULL,
    "VisitId" uuid NOT NULL,
    "BloodPressure" character varying(20) NULL,
    "Pulse" integer NULL,
    "TemperatureC" numeric(4,1) NULL,
    "RespiratoryRate" integer NULL,
    "Spo2" integer NULL,
    "WeightKg" numeric(6,2) NULL,
    "HeightCm" numeric(5,1) NULL,
    "RecordedByUserId" character varying(450) NULL,
    "RecordedByName" character varying(200) NULL,
    "RecordedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_VitalSigns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VitalSigns_ClinicalVisits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "ClinicalVisits" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_VitalSigns_VisitId" ON "VitalSigns" ("VisitId");

CREATE TABLE IF NOT EXISTS "Diagnoses" (
    "Id" uuid NOT NULL,
    "VisitId" uuid NOT NULL,
    "IsPrimary" boolean NOT NULL DEFAULT FALSE,
    "Code" character varying(32) NULL,
    "Description" character varying(500) NOT NULL,
    CONSTRAINT "PK_Diagnoses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Diagnoses_ClinicalVisits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "ClinicalVisits" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_Diagnoses_VisitId" ON "Diagnoses" ("VisitId");

CREATE TABLE IF NOT EXISTS "ClinicalNotes" (
    "Id" uuid NOT NULL,
    "VisitId" uuid NOT NULL,
    "NoteType" character varying(32) NOT NULL DEFAULT 'Progress',
    "Content" text NOT NULL,
    "AuthorUserId" character varying(450) NULL,
    "AuthorName" character varying(200) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ClinicalNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClinicalNotes_ClinicalVisits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "ClinicalVisits" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_ClinicalNotes_VisitId" ON "ClinicalNotes" ("VisitId");

-- -----------------------------------------------------------------------------
-- Death-note provenance: patient remains in the longitudinal record
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "PatientDeathRecords" (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "DateOfDeath" date NULL,
    "Note" character varying(500) NULL,
    "RecordedByUserId" character varying(450) NULL,
    "RecordedByName" character varying(200) NULL,
    "RecordedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "ClearedAt" timestamp with time zone NULL,
    "ClearedByUserId" character varying(450) NULL,
    "ClearedByName" character varying(200) NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_PatientDeathRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PatientDeathRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_PatientDeathRecords_ActivePatient" ON "PatientDeathRecords" ("PatientId") WHERE "IsActive" = TRUE;

COMMIT;

-- -----------------------------------------------------------------------------
-- Reference seed data for local/demo environments
-- -----------------------------------------------------------------------------
BEGIN;

INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES
 ('role-doctor','Doctor','DOCTOR',gen_random_uuid()::text),
 ('role-nurse','Nurse','NURSE',gen_random_uuid()::text),
 ('role-receptionist','Receptionist','RECEPTIONIST',gen_random_uuid()::text),
 ('role-admin','Admin','ADMIN',gen_random_uuid()::text)
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "Patients" ("Id","MedicalRecordNumber","FirstName","LastName","DateOfBirth","Sex","Status","Phone","IsActive","CreatedAt") VALUES
 ('11111111-1111-1111-1111-111111111101','OCR-000001','Marta','Maru','1990-05-12','Female','Active','+251912345678',TRUE,NOW()),
 ('11111111-1111-1111-1111-111111111102','OCR-000002','Dawit','Tesfaye','1985-03-20','Male','Active','+251912345679',TRUE,NOW())
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "PatientAllergies" ("Id","PatientId","Substance","Reaction","Severity","CreatedAt") VALUES
 ('22222222-2222-2222-2222-222222222201','11111111-1111-1111-1111-111111111101','Penicillin','Rash','Severe',NOW())
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "Appointments" ("Id","PatientId","AppointmentDate","StartTime","DurationMinutes","AppointmentType","Status","ProviderName","Reason","CreatedAt") VALUES
 ('44444444-4444-4444-4444-444444444401','11111111-1111-1111-1111-111111111101','2026-09-01','09:00:00',30,'Consultation','Completed','Dr. Samuel Clinician','Fever',NOW())
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "ClinicalVisits" ("Id","PatientId","AppointmentId","VisitDate","VisitType","Status","ChiefComplaint","ClinicianName","CheckInAt","FinalizedAt","CreatedAt") VALUES
 ('55555555-5555-5555-5555-555555555501','11111111-1111-1111-1111-111111111101','44444444-4444-4444-4444-444444444401','2026-09-01 09:15:00+00','Consultation','Final','Fever','Dr. Samuel Clinician','2026-09-01 09:10:00+00','2026-09-01 09:45:00+00',NOW()),
 ('55555555-5555-5555-5555-555555555502','11111111-1111-1111-1111-111111111101',NULL,'2026-09-10 10:00:00+00','Walk-in','Final','Follow-up after fever','Dr. Samuel Clinician','2026-09-10 09:55:00+00','2026-09-10 10:30:00+00',NOW())
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "VitalSigns" ("Id","VisitId","TemperatureC","Pulse","RecordedByName","RecordedAt") VALUES
 ('66666666-6666-6666-6666-666666666601','55555555-5555-5555-5555-555555555501',38.1,90,'Hana Mekonnen','2026-09-01 09:20:00+00'),
 ('66666666-6666-6666-6666-666666666602','55555555-5555-5555-5555-555555555502',36.8,74,'Hana Mekonnen','2026-09-10 10:05:00+00')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "ClinicalNotes" ("Id","VisitId","NoteType","Content","AuthorName","CreatedAt") VALUES
 ('77777777-7777-7777-7777-777777777701','55555555-5555-5555-5555-555555555501','Progress','Visit 1 test record.','Dr. Samuel Clinician','2026-09-01 09:40:00+00'),
 ('77777777-7777-7777-7777-777777777702','55555555-5555-5555-5555-555555555502','Progress','Visit 2 test record.','Dr. Samuel Clinician','2026-09-10 10:25:00+00')
ON CONFLICT ("Id") DO NOTHING;

COMMIT;

-- Revisit acceptance check: Visit 1 remains 38.1 C / pulse 90.
-- SELECT "TemperatureC", "Pulse" FROM "VitalSigns"
-- WHERE "VisitId" = '55555555-5555-5555-5555-555555555501';
